<a href="https://colab.research.google.com/github/shadiyahamza/assignment/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Libraries**

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression #logistic regression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix



# **Loading dataset from google drive**

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
# loading dataset from google drive
# mount the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
filepath = '/content/drive/MyDrive/hy/iris.csv'
df_iris = pd.read_csv(filepath)
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df_iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

# **PREPROCESSING**

In [10]:
# PREPROCESSING
# Iris dataset is consiiderd to be already preprocessed
# so, only encoding is done

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_iris['species'] = le.fit_transform(df_iris['species'])
df_iris.head()

# preparing data
# SPLIT DATA INTO TRAIN AND TEST
from sklearn.model_selection import train_test_split
y = df_iris['species']
X = df_iris.drop('species',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# **Model building**

In [11]:
# preparing data
# SPLIT DATA INTO TRAIN AND TEST
from sklearn.model_selection import train_test_split
y = df_iris['species']
X = df_iris.drop('species',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

Logistic Regresion

In [12]:
# buildibg the logistic regression model
log_reg_model = LogisticRegression()
log_reg_model.fit(X_train,y_train)    #training the model
y_pred = log_reg_model.predict(X_test) #predicting the test data

#evaluate the model
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)
precision = precision_score(y_test,y_pred,average='weighted')
print("Precision:",precision)
recall = recall_score(y_test,y_pred,average='weighted')
print("Recall:",recall)

#overfitting.......... to solve it....
# gather more data


Accuracy: 1.0
Precision: 1.0
Recall: 1.0


In [13]:
#prediction using threshold
y_pred_threshold = (log_reg_model.predict_proba(X_test)[:,1])
#for class1
y_pred_threshold = (y_pred_threshold>0.33).astype(int)

#evaluate the model
accuracy_thresh = accuracy_score(y_test,y_pred_threshold)
print("Accuracy:",accuracy_thresh)
precision_thresh = precision_score(y_test,y_pred_threshold,average='weighted')
print("Precision:",precision_thresh)
recall_thresh = recall_score(y_test,y_pred_threshold,average='weighted')
print("Recall:",recall_thresh)

Accuracy: 0.6333333333333333
Precision: 0.43666666666666665
Recall: 0.6333333333333333


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


KNN (K NEAREST NEIGHBOURS)

In [14]:
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train,y_train)# training happens
y_pred_knn = knn_model.predict(X_test)# prediction happens

#evaluate the model
accuracy = accuracy_score(y_test,y_pred_knn)                                     #classical machine learning models
print("Accuracy:",accuracy)
precision = precision_score(y_test,y_pred_knn,average='weighted')
print("Precision:",precision)
recall = recall_score(y_test,y_pred_knn,average='weighted')
print("Recall:",recall)                                                          #overfitting -- will not analyze general trend -- no.of data is not enough a reason for this
                                                                                 #underfitting

Accuracy: 1.0
Precision: 1.0
Recall: 1.0


uses Naive bayers therorm

In [15]:
df_iris.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [16]:
df_iris.describe()

sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.054000      3.758667     1.198667    1.000000
std        0.828066     0.433594      1.764420     0.763161    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [17]:
nb_model = GaussianNB()
nb_model.fit(X_train,y_train) #training thew model          #FEATURES ARE INDEPENDENT
y_pred_nb = nb_model.predict(X_test) #prediction
#evaluate the model
accuracy = accuracy_score(y_test,y_pred_nb)
print("Accuracy:",accuracy)
precision = precision_score(y_test,y_pred_nb,average='weighted')
print("Precision:",precision)
recall = recall_score(y_test,y_pred_nb,average='weighted')
print("Recall:",recall)                                                           #TARGET MUST BE DEPENDENT ON FEATUERS



Accuracy: 1.0
Precision: 1.0
Recall: 1.0


BUILD SVM CLASSIFIER

In [18]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

nb_model = GaussianNB()
nb_model.fit(X_train, y_train) #Train

# Predict
y_pred_nb = nb_model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy)

precision = precision_score(y_test, y_pred_nb, average='weighted')
print("Naive Bayes Precision:", precision)

recall = recall_score(y_test, y_pred_nb, average='weighted')
print("Naive Bayes Recall:", recall)

confusion_matrix_nb = confusion_matrix(y_test, y_pred_nb)
print("Naive Bayes Confusion Matrix:")
print(confusion_matrix_nb)

Naive Bayes Accuracy: 1.0
Naive Bayes Precision: 1.0
Naive Bayes Recall: 1.0
Naive Bayes Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [19]:
df_iris['species'].unique()

array([0, 1, 2])

Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)# train

# Predict
y_pred_dt = dt_model.predict(X_test)

# Evaluate
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='weighted')
recall_dt = recall_score(y_test, y_pred_dt, average='weighted')
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt)
print("Decision Tree Precision:", precision_dt)
print("Decision Tree Recall:", recall_dt)
print("Decision Tree Confusion Matrix:")
print(conf_matrix_dt)


Decision Tree Accuracy: 1.0
Decision Tree Precision: 1.0
Decision Tree Recall: 1.0
Decision Tree Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Random Forest

In [21]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)#train

# Predict
y_pred_rf = rf_model.predict(X_test)

# Evaluate
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf, average='weighted')
recall_rf = recall_score(y_test, y_pred_rf, average='weighted')
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

print("Random Forest Accuracy:", accuracy_rf)
print("Random Forest Precision:", precision_rf)
print("Random Forest Recall:", recall_rf)
print("Random Forest Confusion Matrix:")
print(conf_matrix_rf)


Random Forest Accuracy: 1.0
Random Forest Precision: 1.0
Random Forest Recall: 1.0
Random Forest Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# **Comparison of Classification Models in Machine Learning**

In [22]:
data = {'Model': ['Logistic Regression', 'KNN', 'Naive Bayes', 'Decision Tree','SVM', 'Random Forest'],
        'Accuracy': [1,1,1,1,1,1],
        'Precision': [1,1,1,1,1,1],
        'Recall': [1,1,1,1,1,1]}
df_results = pd.DataFrame(data)
df_results

Model  Accuracy  Precision  Recall
0  Logistic Regression         1          1       1
1                  KNN         1          1       1
2          Naive Bayes         1          1       1
3        Decision Tree         1          1       1
4                  SVM         1          1       1
5        Random Forest         1          1       1